### model
model_name_or_path: $MODEL_NAME_OR_PATH

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: /home/nfs05/liujx/GithubRepos/SvS-0918/scripts/Meituan/DeepSeek-Config/ds_z3_offload_config.json

### dataset
dataset: $DATASET
template: $TEMPLATE
cutoff_len: $CUTOFF_LEN
overwrite_cache: true
preprocessing_num_workers: 80

### output
output_dir: $OUTPUT_DIR
save_strategy: steps
logging_steps: 5
save_steps: 20
save_total_limit: 2
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: $GRADIENT_ACCUMULATION_STEPS
learning_rate: 0.00001

weight_decay: 0.01
max_grad_norm: 1.0
warmup_ratio: 0.1
num_train_epochs: $NUM_EPOCHS
gradient_checkpointing: true
lr_scheduler_type: cosine
bf16: true
ddp_timeout: 180000000
use_swanlab: true
flash_attn: fa2
optim: paged_adamw_8bit

